name: Laravel Tests

on: [ push ]

jobs:
  tests:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Copy .env.example to .env
        run: cp .env.example .env

      - name: Build the Docker
        run: docker-compose build
      - name: Start the Docker
        run: docker-compose up -d

      - name: Install dependencies
        run: docker-compose exec app composer install
      - name: Run installation artisan command
        run: docker-compose exec app php artisan promodule:install

      - name: Run tests
        run: docker-compose exec app vendor/bin/phpunit
